<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9JTRJBE" name="Hybrent3_8_0rc1.Login" tests="6" failures="0" timestamp="2 Dec 2021 08:49:06 GMT" time="49.662" errors="1">
  <testcase name="LoginWithBlankCrednetials" time="8.718" classname="Hybrent3_8_0rc1.Login"/>
  <testcase name="LoginWithValidCrednetials" time="11.043" classname="Hybrent3_8_0rc1.Login">
    <error type="java.lang.AssertionError" message="expected [Daily Dash] but found []">
      <![CDATA[java.lang.AssertionError: expected [Daily Dash] but found []
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at Hybrent3_8_0rc1.Login.LoginWithValidCrednetials(Login.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- LoginWithValidCrednetials -->
  <testcase name="VerifyWithInvalidSiteNameEnter" time="6.580" classname="Hybrent3_8_0rc1.Login"/>
  <testcase name="VerifyWithValidSiteNameEnter" time="6.653" classname="Hybrent3_8_0rc1.Login"/>
  <testcase name="LoginWithInvalidCrednetials" time="8.005" classname="Hybrent3_8_0rc1.Login"/>
  <testcase name="VerifyWithBlankSiteNameEnter" time="8.663" classname="Hybrent3_8_0rc1.Login"/>
</testsuite> <!-- Hybrent3_8_0rc1.Login -->
